runtime: nodejs18

instance_class: F1

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /.*
  secure: always
  script: auto

# WebSocket support for Socket.io
network:
  session_affinity: true